#!/usr/bin/env python3
"""Generates tests/mock/ApiDump.luau: a trimmed Roblox API table (classes,
their superclass, property types, methods, events; every enum) for the
integration-test mock, so it can reject invalid members at runtime exactly
like the engine does.

Only classes the codebase can touch are kept: every class name that appears
as a string literal in src/ or tests/mock/, plus their ancestors.

Usage:
  python3 tools/gen_api_dump.py path/to/@rbxts/types/include/generated
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from check_api import parse_enums  # noqa: E402

TYPE_CODES = {
    "number": "n",
    "boolean": "b",
    "string": "s",
    "Vector3": "V3",
    "Vector2": "V2",
    "CFrame": "CF",
    "Color3": "C3",
    "UDim2": "U2",
    "UDim": "U",
    "NumberSequence": "NS",
    "ColorSequence": "CS",
    "NumberRange": "NR",
    "Rect": "R",
    "BrickColor": "BC",
    "Font": "F",
}


def parse(paths):
    classes = {}
    current = None
    for path in paths:
        with open(path, encoding="utf-8") as f:
            for line in f:
                m = re.match(r"interface (\w+)(?:<.*?>)?(?: extends (\w+))?", line)
                if m:
                    current = m.group(1)
                    entry = classes.setdefault(current, {"S": None, "P": {}, "M": set(), "E": set()})
                    if m.group(2):
                        entry["S"] = m.group(2).split(",")[0].strip()
                    continue
                if line.startswith("}"):
                    current = None
                    continue
                if not current:
                    continue
                m = re.match(r"\s{4}(?:readonly )?(\w+)\(this", line)
                if m:
                    classes[current]["M"].add(m.group(1))
                    continue
                m = re.match(r"\s{4}(?:readonly )?(\w+)\??: (.+);\s*$", line)
                if m:
                    name, ts = m.group(1), m.group(2).strip()
                    if name.startswith("_nominal"):
                        continue
                    if ts.startswith("RBXScriptSignal"):
                        classes[current]["E"].add(name)
                        continue
                    if ts.startswith("(") or "=>" in ts:
                        classes[current]["P"][name] = "fn"  # assignable callback
                        continue
                    base = ts.split("|")[0].strip()
                    code = TYPE_CODES.get(base)
                    if code is None:
                        em = re.match(r"Enum\.(\w+)", base)
                        if em:
                            code = "E:" + em.group(1)
                        else:
                            code = "?"
                    classes[current]["P"][name] = code
    return classes


def used_names():
    names = set()
    for top in ("src", os.path.join("tests", "mock")):
        for dirpath, _, files in os.walk(os.path.join(ROOT, top)):
            for n in files:
                if n.endswith(".luau") and n != "ApiDump.luau":
                    with open(os.path.join(dirpath, n), encoding="utf-8") as f:
                        names |= set(re.findall(r"\"([A-Z]\w+)\"", f.read()))
    return names


def main():
    gen = sys.argv[1]
    classes = parse([os.path.join(gen, "None.d.ts"), os.path.join(gen, "PluginSecurity.d.ts")])
    enums = parse_enums(os.path.join(gen, "enums.d.ts"))
    wanted = set()
    for name in used_names():
        cur = name
        while cur and cur in classes and cur not in wanted:
            wanted.add(cur)
            cur = classes[cur]["S"]
    out = ["-- GENERATED by tools/gen_api_dump.py from the Roblox API (via @rbxts/types). Do not edit.", "return {", "\tClasses = {"]
    for name in sorted(wanted):
        c = classes[name]
        props = ", ".join(f'{k} = "{v}"' for k, v in sorted(c["P"].items()))
        methods = ", ".join(f'"{m}"' for m in sorted(c["M"]))
        events = ", ".join(f'"{e}"' for e in sorted(c["E"]))
        sup = f'"{c["S"]}"' if c["S"] and c["S"] in classes else "nil"
        out.append(f"\t\t{name} = {{ S = {sup}, P = {{ {props} }}, M = {{ {methods} }}, E = {{ {events} }} }},")
    out.append("\t},")
    out.append("\tEnums = {")
    for name in sorted(enums):
        items = ", ".join(f'"{i}"' for i in sorted(enums[name]))
        out.append(f"\t\t{name} = {{ {items} }},")
    out.append("\t},")
    out.append("}")
    target = os.path.join(ROOT, "tests", "mock", "ApiDump.luau")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(wanted)} classes, {len(enums)} enums -> {target}")


if __name__ == "__main__":
    main()
